configs:
  spider-storage-config:
    content: |
      host: "0.0.0.0"
      port: ${SPIDER_STORAGE_PORT:-50051}
      runtime:
        db:
          host: "spider-database"
          max_connections: ${SPIDER_STORAGE_DB_MAX_CONNECTIONS:-64}
          name: "${SPIDER_DATABASE_NAME:-spider-db}"
          port: ${SPIDER_DATABASE_PORT:-3306}
        inbound_queue:
          cleanup_capacity: ${SPIDER_STORAGE_INBOUND_QUEUE_CLEANUP_CAPACITY:-256}
          commit_capacity: ${SPIDER_STORAGE_INBOUND_QUEUE_COMMIT_CAPACITY:-256}
          task_capacity: ${SPIDER_STORAGE_INBOUND_QUEUE_TASK_CAPACITY:-1048576}
        job_cache_gc:
          gc_interval_sec: ${SPIDER_STORAGE_JOB_CACHE_GC_INTERVAL_SEC:-30}
          terminated_job_retention_sec:
            ${SPIDER_STORAGE_JOB_CACHE_TERMINATED_JOB_RETENTION_SEC:-300}
        task_instance_pool:
          execution_manager_stale_cutoff_sec:
            ${SPIDER_STORAGE_TASK_INSTANCE_POOL_EXECUTION_MANAGER_STALE_CUTOFF_SEC:-60}
          gc_interval_sec: ${SPIDER_STORAGE_TASK_INSTANCE_POOL_GC_INTERVAL_SEC:-30}
          message_channel_capacity:
            ${SPIDER_STORAGE_TASK_INSTANCE_POOL_MESSAGE_CHANNEL_CAPACITY:-128}
