[package]
name = "spider-task-executor"
version = { workspace = true }
edition = { workspace = true }

[lib]
name = "spider_task_executor"
path = "src/lib.rs"

[[bin]]
name = "spider-task-executor"
path = "src/bin/spider_task_executor.rs"

[dependencies]
anyhow = { workspace = true }
bincode = { workspace = true }
bytes = { workspace = true }
futures-util = { workspace = true }
libloading = { workspace = true }
rmp-serde = { workspace = true }
serde = { workspace = true }
spider-core = { workspace = true }
spider-tdl = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["io-std", "io-util", "macros", "rt", "sync", "time"] }
tokio-util = { workspace = true, features = ["codec"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
