[package]
name = "spider-proto-rust"
version = { workspace = true }
edition = { workspace = true }

[lib]
name = "spider_proto_rust"
path = "src/lib.rs"

[dependencies]
prost = { workspace = true }
spider-core = { workspace = true }
spider-utils = { workspace = true }
thiserror = { workspace = true }
tonic = { workspace = true }
tonic-prost = { workspace = true }
tracing = { workspace = true }

[build-dependencies]
tonic-prost-build = { workspace = true }
