version: "3"

includes:
  build: "taskfiles/build.yaml"
  deps: "taskfiles/deps.yaml"
  docs: "docs/tasks.yaml"
  lint: "taskfiles/lint.yaml"
  test: "taskfiles/test.yaml"
  utils: "tools/yscope-dev-utils/exports/taskfiles/utils/utils.yaml"

vars:
  G_BUILD_DIR: "{{.ROOT_DIR}}/build"
  G_BUILD_SPIDER_DIR: "{{.G_BUILD_DIR}}/spider"
  G_SPIDER_CMAKE_CACHE: "{{.G_BUILD_SPIDER_DIR}}/CMakeCache.txt"
  G_SPIDER_COMPILE_COMMANDS_DB: "{{.G_BUILD_SPIDER_DIR}}/compile_commands.json"
  G_BUILD_EXAMPLES_DIR: "{{.G_BUILD_DIR}}/examples"
  G_EXAMPLES_CMAKE_CACHE: "{{.G_BUILD_EXAMPLES_DIR}}/CMakeCache.txt"
  G_EXAMPLES_COMPILE_COMMANDS_DB: "{{.G_BUILD_EXAMPLES_DIR}}/compile_commands.json"
  G_RUST_BUILD_DIR: "{{.G_BUILD_DIR}}/rust-targets"
  G_SRC_SPIDER_DIR: "{{.ROOT_DIR}}/src/spider"
  G_TEST_DIR: "{{.ROOT_DIR}}/tests"
  G_EXAMPLES_DIR: "{{.ROOT_DIR}}/examples"

  G_SRC_PYTHON_DIR: "{{.ROOT_DIR}}/python/spider-py"
  G_BUILD_PYTHON_DIR: "{{.G_BUILD_DIR}}/spider-py"

  # Build parameters
  # NOTE: Defaulting to an empty string is safe since CMake ignores an empty string.
  G_DEPS_MAX_PARALLELISM_PER_TASK: >-
    {{default "" (env "SPIDER_DEPS_MAX_PARALLELISM_PER_TASK")}}
  G_DEPS_DIR: "{{.G_BUILD_DIR}}/deps"
  # These should be kept in-sync with its usage in CMakeLists.txt
  G_DEPS_CMAKE_SETTINGS_DIR: "{{.G_DEPS_DIR}}/cmake-settings"
  G_CMAKE_DEPENDENCY_FILE: "{{.G_DEPS_CMAKE_SETTINGS_DIR}}/all.cmake"

tasks:
  clean:
    cmds:
      - "rm -rf '{{.G_BUILD_DIR}}'"

  config-cmake-project:
    internal: true
    sources:
      - "{{.TASKFILE}}"
      - "CMakeLists.txt"
      - "examples/quick-start/CMakeLists.txt"
    generates:
      - "{{.G_SPIDER_CMAKE_CACHE}}"
      - "{{.G_SPIDER_COMPILE_COMMANDS_DB}}"
      - "{{.G_EXAMPLES_CMAKE_CACHE}}"
      - "{{.G_EXAMPLES_COMPILE_COMMANDS_DB}}"
    cmds:
      - >-
       cmake -S '{{.ROOT_DIR}}'
       -DSPIDER_CMAKE_DEPENDENCY_FILE='{{.G_CMAKE_DEPENDENCY_FILE}}'
       -B '{{.G_BUILD_SPIDER_DIR}}'
      - "cmake -S '{{.ROOT_DIR}}/examples/quick-start' -B '{{.G_BUILD_EXAMPLES_DIR}}'"

  init:
    internal: true
    silent: true
    run: "once"
    cmds:
      - "mkdir -p '{{.G_BUILD_DIR}}'"
      - "mkdir -p '{{.G_BUILD_SPIDER_DIR}}'"
