[package]
name = "tdl-integration"
version = { workspace = true }
edition = { workspace = true }
publish = false

[lib]
name = "tdl_integration"
path = "src/lib.rs"

[[test]]
name = "complex"
path = "tests/complex.rs"

[[test]]
name = "init"
path = "tests/init.rs"

[dev-dependencies]
anyhow = { workspace = true }
huntsman-complex-types = { workspace = true }
rmp-serde = { workspace = true }
spider-core = { workspace = true }
spider-task-executor = { workspace = true }
spider-tdl = { workspace = true }
