# Required variables:
# - SPIDER_IMAGE_TAG
# - SPIDER_STORAGE_DB_USERNAME
# - SPIDER_STORAGE_DB_PASSWORD
# - SPIDER_DATABASE_ROOT_PASSWORD
name: "spider"

x-service-defaults: &service_defaults
  logging:
    driver: "local"
  restart: "${SPIDER_RESTART_POLICY:-on-failure:3}"
  stop_grace_period: "60s"

x-healthcheck-defaults: &healthcheck_defaults
  interval: "30s"
  retries: 3
  start_interval: "2s"
  start_period: "60s"
  timeout: "2s"

services:
  spider-database:
    <<: *service_defaults
    image: "mariadb:10.11.16"
    pull_policy: "always"
    environment:
      MYSQL_DATABASE: "spider-db"
      MYSQL_PASSWORD: "${SPIDER_STORAGE_DB_PASSWORD:?Please set a value.}"
      MYSQL_ROOT_PASSWORD: "${SPIDER_DATABASE_ROOT_PASSWORD:?Please set a value.}"
      MYSQL_USER: "${SPIDER_STORAGE_DB_USERNAME:?Please set a value.}"
    volumes:
      - type: "volume"
        source: "spider-database-data"
        target: "/var/lib/mysql"
    healthcheck:
      <<: *healthcheck_defaults
      test: [
        "CMD",
        "mysqladmin", "ping",
        "--silent",
        "-h", "127.0.0.1",
        "-u", "${SPIDER_STORAGE_DB_USERNAME:?Please set a value.}",
        "--password=${SPIDER_STORAGE_DB_PASSWORD:?Please set a value.}",
      ]

  spider-storage:
    <<: *service_defaults
    image: >-
      ghcr.io/y-scope/spider/storage:${SPIDER_IMAGE_TAG:?Please set a value.}
    pull_policy: "always"
    command: [
      "spider-storage",
      "--config", "/etc/spider/storage.yaml",
    ]
    environment:
      RUST_LOG: "${SPIDER_STORAGE_RUST_LOG:-INFO}"
      SPIDER_STORAGE_DB_PASSWORD: "${SPIDER_STORAGE_DB_PASSWORD:?Please set a value.}"
      SPIDER_STORAGE_DB_USERNAME: "${SPIDER_STORAGE_DB_USERNAME:?Please set a value.}"
    configs:
      - source: "spider-storage-config"
        target: "/etc/spider/storage.yaml"
    depends_on:
      spider-database:
        condition: "service_healthy"
        restart: true
    healthcheck:
      <<: *healthcheck_defaults
      test: [
        "CMD",
        "timeout", "2",
        "bash", "-c", "</dev/tcp/127.0.0.1/50051",
      ]

  spider-scheduler:
    <<: *service_defaults
    image: >-
      ghcr.io/y-scope/spider/scheduler:${SPIDER_IMAGE_TAG:?Please set a value.}
    pull_policy: "always"
    command: [
      "spider-scheduler",
      "--config", "/etc/spider/scheduler.yaml",
    ]
    environment:
      RUST_LOG: "${SPIDER_SCHEDULER_RUST_LOG:-INFO}"
    ports:
      - host_ip: "${SPIDER_SCHEDULER_HOST:-127.0.0.1}"
        published: "${SPIDER_SCHEDULER_HOST_PORT:-50052}"
        target: 50052
    configs:
      - source: "spider-scheduler-config"
        target: "/etc/spider/scheduler.yaml"
    depends_on:
      spider-storage:
        condition: "service_healthy"
        restart: true
    healthcheck:
      <<: *healthcheck_defaults
      test: [
        "CMD",
        "timeout", "2",
        "bash", "-c", "</dev/tcp/127.0.0.1/50052",
      ]

  spider-worker:
    <<: *service_defaults
    image: >-
      ghcr.io/y-scope/spider/worker:${SPIDER_IMAGE_TAG:?Please set a value.}
    pull_policy: "always"
    command: [
      "spider-execution-manager",
      "--config", "/etc/spider/worker.yaml",
    ]
    environment:
      RUST_LOG: "${SPIDER_WORKER_RUST_LOG:-INFO}"
    configs:
      - source: "spider-worker-config"
        target: "/etc/spider/worker.yaml"
    depends_on:
      spider-scheduler:
        condition: "service_healthy"
        restart: true
      spider-storage:
        condition: "service_healthy"
        restart: true
    deploy:
      replicas: "${SPIDER_WORKER_REPLICAS:-4}"

configs:
  spider-scheduler-config:
    file: "./config/scheduler.yaml"
  spider-storage-config:
    file: "./config/storage.yaml"
  spider-worker-config:
    file: "./config/worker.yaml"

volumes:
  spider-database-data:
