[package]
name = "huntsman-complex"
version = { workspace = true }
edition = { workspace = true }
publish = false

[lib]
crate-type = ["cdylib"]
name = "huntsman_complex"
path = "src/lib.rs"

[dependencies]
huntsman-complex-types = { workspace = true }
serde = { workspace = true }
spider-tdl = { workspace = true, features = ["derive"] }
