[package]
name = "huntsman-nn-tasks"
version = { workspace = true }
edition = { workspace = true }
publish = false

[lib]
crate-type = ["cdylib"]
name = "nn"
path = "src/lib.rs"

[dependencies]
huntsman-nn-core = { workspace = true }
serde = { workspace = true }
spider-tdl = { workspace = true, features = ["derive"] }
