[package]
name = "e2e"
version = { workspace = true }
edition = { workspace = true }
publish = false

[dependencies]
anyhow = { workspace = true }
spider-client = { workspace = true }
spider-core = { workspace = true }
tokio = {
  workspace = true,
  features = ["macros", "rt-multi-thread", "sync", "time"]
}
tonic = { workspace = true }
