apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: {{ include "spider.fullname" . }}-config
  labels:
    {{- include "spider.labels" . | nindent 4 }}
data:
  storage.yaml: |
    host: "0.0.0.0"
    port: {{ .Values.spiderConfig.storage_endpoint.port }}
    runtime:
      db_config:
        host: {{ include "spider.databaseHost" . | quote }}
        port: {{ include "spider.databasePort" . }}
        name: {{ .Values.spiderConfig.database.name | quote }}
        username: {{ .Values.spiderConfig.database.username | quote }}
        password: {{ .Values.spiderConfig.database.password | quote }}
        max_connections: {{ .Values.spiderConfig.storage.max_connections }}
      {{- with omit .Values.spiderConfig.storage "max_connections" }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
