apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: {{ include "spider.componentFullname" (dict "root" . "component" "config") }}
  labels:
    {{- include "spider.labels" . | nindent 4 }}
data:
  scheduler.yaml: |
    connection_pool_size: {{ .Values.spiderConfig.scheduler.connection_pool_size }}
    host: "0.0.0.0"
    port: {{ .Values.spiderConfig.scheduler.port }}
    runtime:
      advertised_endpoint:
        host: {{ include "spider.componentFullname" (dict "root" . "component" "scheduler") | quote }}
        port: {{ .Values.spiderConfig.scheduler.port }}
      {{- $scheduler := .Values.spiderConfig.scheduler.runtime.scheduler }}
      {{- $algorithm := keys $scheduler | first }}
      scheduler: !{{ $algorithm }}
        {{- toYaml (index $scheduler $algorithm) | nindent 8 }}
    storage_endpoint:
      host: {{ include "spider.componentFullname" (dict "root" . "component" "storage") | quote }}
      port: {{ .Values.spiderConfig.storage.port }}
  storage.yaml: |
    host: "0.0.0.0"
    port: {{ .Values.spiderConfig.storage.port }}
    runtime:
      db_config:
        host: {{ include "spider.databaseHost" . | quote }}
        max_connections: {{ .Values.spiderConfig.database.max_connections }}
        name: {{ .Values.spiderConfig.database.name | quote }}
        port: {{ include "spider.databasePort" . }}
      {{- with .Values.spiderConfig.storage.runtime }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
