{{- if has "database" .Values.spiderConfig.bundled }}
apiVersion: "v1"
kind: "Secret"
metadata:
  name: {{ include "spider.fullname" . }}-database
  labels:
    {{- include "spider.labels" . | nindent 4 }}
    app.kubernetes.io/component: "database"
type: "Opaque"
stringData:
  username: {{ .Values.spiderConfig.database.username | quote }}
  password: {{ .Values.spiderConfig.database.password | quote }}
  root_password: {{ .Values.spiderConfig.database.root_password | quote }}
{{- end }}
