apiVersion: "v1"
kind: "Service"
metadata:
  name: {{ include "spider.componentFullname" (dict "root" . "component" "scheduler") }}
  labels:
    {{- include "spider.labels" . | nindent 4 }}
    app.kubernetes.io/component: "scheduler"
spec:
  selector:
    {{- include "spider.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: "scheduler"
  ports:
    - name: "grpc"
      port: {{ .Values.spiderConfig.scheduler.port }}
      targetPort: "grpc"
