apiVersion: "v1"
kind: "Service"
metadata:
  name: {{ include "spider.componentFullname" (dict "root" . "component" "storage") }}
  labels:
    {{- include "spider.labels" . | nindent 4 }}
    app.kubernetes.io/component: "storage"
spec:
  selector:
    {{- include "spider.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: "storage"
  ports:
    - name: "grpc"
      port: {{ .Values.spiderConfig.storage.port }}
      targetPort: "grpc"
