[package]
name = "spider-tdl"
version = { workspace = true }
edition = { workspace = true }

[lib]
name = "spider_tdl"
path = "src/lib.rs"

[[test]]
name = "test_task_macro"
path = "tests/test_task_macro.rs"
required-features = ["derive"]

[dependencies]
const-str = { workspace = true }
rmp-serde = { workspace = true }
serde = { workspace = true }
spider-core = { workspace = true }
spider-tdl-derive = { workspace = true, optional = true }
thiserror = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
rmp-serde = { workspace = true }
serde = { workspace = true }
spider-core = { workspace = true }

[features]
default = []
derive = ["dep:spider-tdl-derive"]
