[package]
name = "spider-core"
version = { workspace = true }
edition = { workspace = true }

[lib]
name = "spider_core"
path = "src/lib.rs"

[dependencies]
non-empty-string = { workspace = true }
rand = { workspace = true }
rmp-serde = { workspace = true }
semver = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
spider-derive = { workspace = true }
spider-utils = { workspace = true }
sqlx = { workspace = true }
strum = { workspace = true }
thiserror = { workspace = true }
zstd = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tokio-util = { workspace = true, features = ["rt"] }
