//! Task execution traits and runtime handler.
//!
//! This module defines the [`Task`] trait (implemented by the `#[task]` proc-macro for each
//! user-defined task function), the [`TaskHandler`] trait (the type-erased interface used by the
//! registration macro's dispatch table), and [`TaskHandlerImpl`] (the bridge between them).

use std::marker::PhantomData;

use crate::{
    error::TdlError,
    task_context::TaskContext,
    wire::{TaskInputsSerializer, TaskOutputsSerializer},
};

/// The result of executing a task through the [`TaskHandler`] interface.
///
/// Both variants carry a byte buffer:
///
/// * [`ExecutionResult::Ok`] holds wire-format-encoded output payloads.
/// * [`ExecutionResult::Err`] holds a msgpack-encoded [`TdlError`].
pub type ExecutionResult = std::result::Result<Vec<u8>, Vec<u8>>;

/// Trait implemented by the `#[task]` proc-macro for each user-defined task function.
///
/// It is intended to be implemented by the proc-macro's generated code. Manually implementing this
/// trait must follow the contract outlined in the docstrings.
///
/// The proc-macro generates a marker struct, a params struct, and an impl of this trait that wires
/// deserialized parameters into the user's function body.
pub trait Task {
    /// The deserialized parameter struct (generated by the proc-macro, excludes [`TaskContext`]).
    type Params: for<'deserializer_lifetime> serde::Deserialize<'deserializer_lifetime>;

    /// The return type of the task (must be a tuple, even for single values).
    ///
    /// NOTE: Unfortunately, the tuple trait is a nightly-only feature. Otherwise, we should enforce
    /// the type to implement [`std::marker::Tuple`]. For now, the type error can only be reported
    /// at runtime.
    type Return: serde::Serialize;

    /// The name of the task, used as the lookup key in the registration table.
    const NAME: &'static str;

    /// Executes the task with the given context and deserialized parameters.
    ///
    /// # Parameters
    ///
    /// * `ctx` - The runtime metadata passed to every task.
    /// * `params` - The deserialized task parameter struct.
    ///
    /// # Returns
    ///
    /// The task's return tuple on success.
    ///
    /// # Errors
    ///
    /// Returns a [`TdlError`] on failure.
    fn execute(ctx: TaskContext, params: Self::Params) -> Result<Self::Return, TdlError>;

    /// Serializes the return tuple into wire-format bytes.
    ///
    /// # Parameters
    ///
    /// * `result` - The task's return tuple.
    ///
    /// # Returns
    ///
    /// The wire-format byte stream on success.
    ///
    /// # Errors
    ///
    /// Returns an error if:
    ///
    /// * [`TdlError::SerializationError`] if it fails to serialize the return tuple.
    fn serialize_return(result: &Self::Return) -> Result<Vec<u8>, TdlError> {
        TaskOutputsSerializer::from_tuple(result)
            .map_err(|e| TdlError::SerializationError(e.to_string()))
    }
}

/// Type-erased task execution interface.
///
/// Used by the registration macro's dispatch table to invoke tasks by name without knowing the
/// concrete [`Task`] type. Implementations must be thread-safe since the dispatch table is a
/// `static` object shared across threads.
pub trait TaskHandler: Send + Sync {
    /// Executes the task from raw serialized inputs.
    ///
    /// # Parameters
    ///
    /// * `raw_ctx` - Msgpack-encoded [`TaskContext`].
    /// * `raw_args` - Wire-format-encoded task inputs.
    ///
    /// # Returns
    ///
    /// The serialized return tuple (forwarded from [`Task::execute`]) on success.
    ///
    /// # Errors
    ///
    /// The serialized [`TdlError`] (forwarded from [`Task::execute`]) on failure.
    fn execute_raw(&self, raw_ctx: &[u8], raw_args: &[u8]) -> ExecutionResult;

    /// # Returns
    ///
    /// The task's registered name ([`Task::NAME`]).
    fn name(&self) -> &'static str;
}

/// Bridges a concrete [`Task`] implementation to the type-erased [`TaskHandler`] interface.
///
/// Handles deserialization of [`TaskContext`] (from msgpack) and task parameters (from wire
/// format), delegates to [`Task::execute`], and serializes the result back into bytes.
///
/// # Type Parameters
///
/// * `TaskType` - The concrete [`Task`] implementation.
pub struct TaskHandlerImpl<TaskType: Task> {
    _marker: PhantomData<TaskType>,
}

impl<TaskType: Task> TaskHandlerImpl<TaskType> {
    /// Factory function.
    ///
    /// # Returns
    ///
    /// A newly created handler for the given task type.
    #[must_use]
    pub const fn new() -> Self {
        Self {
            _marker: PhantomData,
        }
    }
}

impl<TaskType: Task> Default for TaskHandlerImpl<TaskType> {
    fn default() -> Self {
        Self::new()
    }
}

impl<TaskType: Task + Send + Sync> TaskHandler for TaskHandlerImpl<TaskType> {
    fn execute_raw(&self, raw_ctx: &[u8], raw_args: &[u8]) -> ExecutionResult {
        let ctx: TaskContext = rmp_serde::from_slice(raw_ctx).map_err(|e| {
            serialize_error(&TdlError::DeserializationError(format!(
                "failed to deserialize `TaskContext`: {e}"
            )))
        })?;
        let params: TaskType::Params = TaskInputsSerializer::deserialize(raw_args)
            .map_err(|e| serialize_error(&TdlError::DeserializationError(e.to_string())))?;
        let result_tuple = TaskType::execute(ctx, params).map_err(|e| serialize_error(&e))?;
        TaskType::serialize_return(&result_tuple).map_err(|e| serialize_error(&e))
    }

    fn name(&self) -> &'static str {
        TaskType::NAME
    }
}

/// # Returns
///
/// The given `err` serialized as a msgpack byte stream.
///
/// # Panics
///
/// Panics if the serialization fails ([`rmp_serde::to_vec`]). The messagepack serialization should
/// always success.
fn serialize_error(err: &TdlError) -> Vec<u8> {
    rmp_serde::to_vec(err).expect("failed to serialize `TdlError` as msgpack")
}

#[cfg(test)]
mod tests {
    use serde::{Deserialize, Serialize};
    use spider_core::types::{
        id::{JobId, ResourceGroupId, TaskId},
        io::TaskInput,
    };

    use super::*;
    use crate::{
        error::TdlError,
        r#std::int32,
        task_context::TaskContext,
        wire::{TaskInputsSerializer, TaskOutputsSerializer},
    };

    const INTENTIONAL_FAILURE: &str = "intentional failure";

    #[derive(Deserialize)]
    struct AddParams {
        a: int32,
        b: int32,
    }

    struct Add;

    impl Add {
        fn make_inputs(a: int32, b: int32) -> anyhow::Result<Vec<u8>> {
            let mut inputs = TaskInputsSerializer::new();
            inputs.append(TaskInput::ValuePayload(rmp_serde::to_vec(&a)?))?;
            inputs.append(TaskInput::ValuePayload(rmp_serde::to_vec(&b)?))?;
            Ok(inputs.release())
        }
    }

    impl Task for Add {
        type Params = AddParams;
        type Return = (int32,);

        const NAME: &'static str = "test::add";

        fn execute(_ctx: TaskContext, params: Self::Params) -> Result<Self::Return, TdlError> {
            Ok((params.a + params.b,))
        }
    }

    #[derive(Deserialize)]
    struct EmptyParams {}

    struct AlwaysFail;

    impl Task for AlwaysFail {
        type Params = EmptyParams;
        type Return = (int32,);

        const NAME: &'static str = "test::fail";

        fn execute(_ctx: TaskContext, _params: Self::Params) -> Result<Self::Return, TdlError> {
            Err(TdlError::ExecutionError(INTENTIONAL_FAILURE.to_owned()))
        }
    }

    #[derive(Serialize)]
    struct IllegalReturn {
        value: int32,
    }

    /// Illegal [`Task`] impl: `Return` is a struct rather than a tuple. Because the tuple
    /// constraint is runtime-checked (see the [`Task::Return`] docstring), such an impl compiles
    /// but fails inside [`TaskHandler::execute_raw`] at the serialization step.
    struct Illegal;

    impl Task for Illegal {
        type Params = EmptyParams;
        type Return = IllegalReturn;

        const NAME: &'static str = "test::illegal";

        fn execute(_ctx: TaskContext, _params: Self::Params) -> Result<Self::Return, TdlError> {
            Ok(IllegalReturn { value: 0 })
        }
    }

    fn make_encoded_ctx() -> Vec<u8> {
        let ctx = TaskContext {
            job_id: JobId::new(),
            task_id: TaskId::new(),
            task_instance_id: 1,
            resource_group_id: ResourceGroupId::new(),
        };
        rmp_serde::to_vec(&ctx).expect("failed to serialize `TaskContext`")
    }

    /// Asserts the given result contains a deserialization error
    /// (`[TdlError::DeserializationError]`).
    fn assert_deserialization_failure(result: ExecutionResult) {
        match result {
            Ok(_) => panic!("expected error"),
            Err(bytes) => {
                let err: TdlError =
                    rmp_serde::from_slice(&bytes).expect("failed to deserialize error");
                assert!(matches!(err, TdlError::DeserializationError(_)));
            }
        }
    }

    #[test]
    fn handler_success() -> anyhow::Result<()> {
        const A: int32 = 10;
        const B: int32 = 32;

        let handler = TaskHandlerImpl::<Add>::new();
        assert_eq!(handler.name(), "test::add");

        let raw_ctx = make_encoded_ctx();
        let raw_args = Add::make_inputs(A, B)?;

        let result = handler.execute_raw(&raw_ctx, &raw_args);
        match result {
            Ok(bytes) => {
                let outputs = TaskOutputsSerializer::deserialize(&bytes)?;
                assert_eq!(outputs.len(), 1);
                let sum: int32 = rmp_serde::from_slice(&outputs[0])?;
                assert_eq!(sum, A + B);
            }
            Err(bytes) => {
                let err: TdlError = rmp_serde::from_slice(&bytes)?;
                panic!("unexpected error: {err}");
            }
        }
        Ok(())
    }

    #[test]
    fn handler_task_error() -> anyhow::Result<()> {
        let handler = TaskHandlerImpl::<AlwaysFail>::new();

        let raw_ctx = make_encoded_ctx();
        let raw_args = TaskInputsSerializer::new().release();

        let result = handler.execute_raw(&raw_ctx, &raw_args);
        match result {
            Ok(_) => panic!("expected error"),
            Err(bytes) => {
                let err: TdlError = rmp_serde::from_slice(&bytes)?;
                assert!(
                    matches!(err, TdlError::ExecutionError(ref msg) if msg == INTENTIONAL_FAILURE)
                );
            }
        }
        Ok(())
    }

    #[test]
    fn handler_bad_ctx() -> anyhow::Result<()> {
        let handler = TaskHandlerImpl::<Add>::new();
        let raw_args = Add::make_inputs(1, 2)?;

        // 0xC1 is a reserved/invalid msgpack byte.
        let result = handler.execute_raw(&[0xc1], &raw_args);
        assert_deserialization_failure(result);
        Ok(())
    }

    #[test]
    fn handler_bad_inputs() {
        let handler = TaskHandlerImpl::<Add>::new();
        let raw_ctx = make_encoded_ctx();

        // Pass truncated wire data.
        let result = handler.execute_raw(&raw_ctx, &[0x01]);
        assert_deserialization_failure(result);
    }

    #[test]
    fn handler_illegal_non_tuple_return() -> anyhow::Result<()> {
        let handler = TaskHandlerImpl::<Illegal>::new();
        let raw_ctx = make_encoded_ctx();
        let raw_args = TaskInputsSerializer::new().release();

        let result = handler.execute_raw(&raw_ctx, &raw_args);
        match result {
            Ok(_) => panic!("expected serialization error for non-tuple return"),
            Err(bytes) => {
                let err: TdlError = rmp_serde::from_slice(&bytes)?;
                assert!(matches!(err, TdlError::SerializationError(_)));
            }
        }
        Ok(())
    }
}
