//! Task execution traits and runtime handler.
//!
//! This module defines the [`Task`] trait (implemented by the `#[task]` proc-macro for each
//! user-defined task function), the [`TaskHandler`] trait (the type-erased interface used by the
//! registration macro's dispatch table), and [`TaskHandlerImpl`] (the bridge between them).

use std::marker::PhantomData;

use crate::{
    error::TdlError,
    task_context::TaskContext,
    wire::{TaskInputs, TaskOutputs},
};

/// The result of executing a task through the [`TaskHandler`] interface.
///
/// Both variants carry a byte buffer: `Outputs` holds wire-format-encoded output payloads, and
/// `Error` holds a msgpack-encoded [`TdlError`].
pub enum ExecutionResult {
    /// Wire-format-encoded output payloads (one per return-tuple element).
    Outputs(Vec<u8>),

    /// Msgpack-encoded [`TdlError`].
    Error(Vec<u8>),
}

/// Trait implemented by the `#[task]` proc-macro for each user-defined task function.
///
/// The proc-macro generates a marker struct, a params struct, and an impl of this trait that
/// wires deserialized parameters into the user's function body.
pub trait Task {
    /// The name of the task, used as the lookup key in the registration table.
    const NAME: &'static str;

    /// The deserialized parameter struct (generated by the proc-macro, excludes [`TaskContext`]).
    type Params: for<'de> serde::Deserialize<'de>;

    /// The return type of the task (always a tuple, even for single values).
    type Return: serde::Serialize;

    /// Executes the task with the given context and deserialized parameters.
    ///
    /// # Returns
    ///
    /// The task's return tuple on success.
    ///
    /// # Errors
    ///
    /// Returns a [`TdlError`] on failure.
    fn execute(ctx: TaskContext, params: Self::Params) -> Result<Self::Return, TdlError>;

    /// Serializes the return tuple into wire-format bytes.
    ///
    /// The default implementation uses [`TaskOutputs::serialize_from`] which drives serde's
    /// `Serialize` impl for the tuple, decomposing it into individually msgpack-encoded wire
    /// payloads. The proc-macro does not need to generate this method.
    ///
    /// # Returns
    ///
    /// The wire-format byte stream on success.
    ///
    /// # Errors
    ///
    /// Returns a [`TdlError`] if serialization of any element fails.
    fn serialize_return(result: &Self::Return) -> Result<Vec<u8>, TdlError> {
        TaskOutputs::serialize_from(result).map_err(|e| TdlError::SerializationError(e.to_string()))
    }
}

/// Type-erased task execution interface.
///
/// Used by the registration macro's dispatch table to invoke tasks by name without knowing the
/// concrete [`Task`] type. Implementations must be thread-safe since the dispatch table is a
/// `static` shared across threads.
pub trait TaskHandler: Send + Sync {
    /// Executes the task from raw serialized inputs.
    ///
    /// # Parameters
    ///
    /// * `raw_ctx` - Msgpack-encoded [`TaskContext`].
    /// * `raw_args` - Wire-format-encoded task inputs.
    ///
    /// # Returns
    ///
    /// [`ExecutionResult::Outputs`] on success, [`ExecutionResult::Error`] on failure.
    fn execute_raw(&self, raw_ctx: &[u8], raw_args: &[u8]) -> ExecutionResult;

    /// Returns the task's registered name ([`Task::NAME`]).
    fn name(&self) -> &'static str;
}

/// Bridges a concrete [`Task`] implementation to the type-erased [`TaskHandler`] interface.
///
/// Handles deserialization of [`TaskContext`] (from msgpack) and task parameters (from wire
/// format), delegates to [`Task::execute`], and serializes the result back into bytes.
///
/// # Type Parameters
///
/// * `TaskType` - The concrete [`Task`] implementation (typically the marker struct generated by
///   the `#[task]` proc-macro).
pub struct TaskHandlerImpl<TaskType: Task> {
    _marker: PhantomData<TaskType>,
}

impl<TaskType: Task> Default for TaskHandlerImpl<TaskType> {
    fn default() -> Self {
        Self::new()
    }
}

impl<TaskType: Task> TaskHandlerImpl<TaskType> {
    /// Creates a new handler for the given task type.
    #[must_use]
    pub const fn new() -> Self {
        Self {
            _marker: PhantomData,
        }
    }
}

impl<TaskType: Task + Send + Sync> TaskHandler for TaskHandlerImpl<TaskType> {
    fn execute_raw(&self, raw_ctx: &[u8], raw_args: &[u8]) -> ExecutionResult {
        // 1. Deserialize TaskContext (msgpack).
        let ctx: TaskContext = match rmp_serde::from_slice(raw_ctx) {
            Ok(c) => c,
            Err(e) => {
                return serialize_error(&TdlError::DeserializationError(format!(
                    "failed to deserialize TaskContext: {e}"
                )));
            }
        };

        // 2. Deserialize task parameters (wire format).
        let params: TaskType::Params = match TaskInputs::deserialize(raw_args) {
            Ok(p) => p,
            Err(e) => {
                return serialize_error(&TdlError::DeserializationError(e.to_string()));
            }
        };

        // 3. Execute the user's task function.
        let result = match TaskType::execute(ctx, params) {
            Ok(r) => r,
            Err(ref e) => return serialize_error(e),
        };

        // 4. Serialize the return tuple into wire-format bytes.
        match TaskType::serialize_return(&result) {
            Ok(bytes) => ExecutionResult::Outputs(bytes),
            Err(ref e) => serialize_error(e),
        }
    }

    fn name(&self) -> &'static str {
        TaskType::NAME
    }
}

/// Serializes a [`TdlError`] into an [`ExecutionResult::Error`].
fn serialize_error(err: &TdlError) -> ExecutionResult {
    let bytes = rmp_serde::to_vec(err).expect("TdlError msgpack serialization failed");
    ExecutionResult::Error(bytes)
}

#[cfg(test)]
mod tests {
    use spider_core::types::id::{JobId, TaskId};

    use super::{ExecutionResult, Task, TaskHandler, TaskHandlerImpl};
    use crate::{
        error::TdlError,
        task_context::TaskContext,
        tdl_types::int32,
        wire::{TaskInputs, TaskOutputs},
    };

    struct AddTask;

    #[derive(serde::Deserialize)]
    struct AddTaskParams {
        a: int32,
        b: int32,
    }

    impl Task for AddTask {
        type Params = AddTaskParams;
        type Return = (int32,);

        const NAME: &'static str = "test::add";

        fn execute(_ctx: TaskContext, params: Self::Params) -> Result<Self::Return, TdlError> {
            Ok((params.a + params.b,))
        }
    }

    struct FailTask;

    #[derive(serde::Deserialize)]
    struct EmptyParams {}

    impl Task for FailTask {
        type Params = EmptyParams;
        type Return = (int32,);

        const NAME: &'static str = "test::fail";

        fn execute(_ctx: TaskContext, _params: Self::Params) -> Result<Self::Return, TdlError> {
            Err(TdlError::ExecutionError("intentional failure".to_owned()))
        }
    }

    fn make_ctx() -> TaskContext {
        TaskContext {
            job_id: JobId::new(),
            task_id: TaskId::new(),
            task_instance_id: 1,
        }
    }

    fn encode_ctx(ctx: &TaskContext) -> Vec<u8> {
        rmp_serde::to_vec(ctx).expect("TaskContext serialization failed")
    }

    fn make_inputs(a: int32, b: int32) -> Vec<u8> {
        let mut inputs = TaskInputs::new();
        inputs
            .append(spider_core::types::io::TaskInput::ValuePayload(
                rmp_serde::to_vec(&a).expect("msgpack encoding failed"),
            ))
            .expect("append failed");
        inputs
            .append(spider_core::types::io::TaskInput::ValuePayload(
                rmp_serde::to_vec(&b).expect("msgpack encoding failed"),
            ))
            .expect("append failed");
        inputs.release()
    }

    #[test]
    fn handler_success() -> anyhow::Result<()> {
        let handler = TaskHandlerImpl::<AddTask>::new();
        assert_eq!(handler.name(), "test::add");

        let ctx = make_ctx();
        let raw_ctx = encode_ctx(&ctx);
        let raw_args = make_inputs(10, 32);

        let result = handler.execute_raw(&raw_ctx, &raw_args);
        match result {
            ExecutionResult::Outputs(bytes) => {
                let outputs = TaskOutputs::deserialize(&bytes)?;
                assert_eq!(outputs.len(), 1);
                let sum: int32 = rmp_serde::from_slice(&outputs[0])?;
                assert_eq!(sum, 42);
            }
            ExecutionResult::Error(bytes) => {
                let err: TdlError = rmp_serde::from_slice(&bytes)?;
                panic!("unexpected error: {err}");
            }
        }
        Ok(())
    }

    #[test]
    fn handler_task_error() -> anyhow::Result<()> {
        let handler = TaskHandlerImpl::<FailTask>::new();

        let ctx = make_ctx();
        let raw_ctx = encode_ctx(&ctx);
        let raw_args = TaskInputs::new().release(); // empty params

        let result = handler.execute_raw(&raw_ctx, &raw_args);
        match result {
            ExecutionResult::Outputs(_) => panic!("expected error"),
            ExecutionResult::Error(bytes) => {
                let err: TdlError = rmp_serde::from_slice(&bytes)?;
                assert!(
                    matches!(err, TdlError::ExecutionError(ref msg) if msg == "intentional failure")
                );
            }
        }
        Ok(())
    }

    #[test]
    fn handler_bad_ctx() -> anyhow::Result<()> {
        let handler = TaskHandlerImpl::<AddTask>::new();
        let raw_args = make_inputs(1, 2);

        // Pass garbage as TaskContext.
        let result = handler.execute_raw(&[0xc1], &raw_args);
        match result {
            ExecutionResult::Outputs(_) => panic!("expected error"),
            ExecutionResult::Error(bytes) => {
                let err: TdlError = rmp_serde::from_slice(&bytes)?;
                assert!(matches!(err, TdlError::DeserializationError(_)));
            }
        }
        Ok(())
    }

    #[test]
    fn handler_bad_inputs() -> anyhow::Result<()> {
        let handler = TaskHandlerImpl::<AddTask>::new();
        let ctx = make_ctx();
        let raw_ctx = encode_ctx(&ctx);

        // Pass truncated wire data.
        let result = handler.execute_raw(&raw_ctx, &[0x01]);
        match result {
            ExecutionResult::Outputs(_) => panic!("expected error"),
            ExecutionResult::Error(bytes) => {
                let err: TdlError = rmp_serde::from_slice(&bytes)?;
                assert!(matches!(err, TdlError::DeserializationError(_)));
            }
        }
        Ok(())
    }
}
