[package]
name = "task-executor-tests"
version = { workspace = true }
edition = { workspace = true }
publish = false

[lib]
name = "task_executor_tests"
path = "src/lib.rs"

[[test]]
name = "executor"
path = "tests/test_executor.rs"

[[test]]
name = "overhead_instrument"
path = "tests/overhead_instrument.rs"

[[test]]
name = "process_pool"
path = "tests/test_process_pool.rs"

[dev-dependencies]
integration-test-tasks = { workspace = true }
rmp-serde = { workspace = true }
spider-core = { workspace = true }
spider-execution-manager = { workspace = true }
spider-task-executor = { workspace = true }
spider-tdl = { workspace = true }
tabled = { workspace = true }
test-utils = { workspace = true }
tokio = {
  workspace = true,
  features = ["io-util", "macros", "rt", "rt-multi-thread", "time"]
}
tokio-util = { workspace = true }
