[package]
name = "spider-execution-manager"
version = { workspace = true }
edition = { workspace = true }

[lib]
name = "spider_execution_manager"
path = "src/lib.rs"

[[bin]]
name = "spider-execution-manager"
path = "src/bin/execution_manager.rs"

[dependencies]
async-trait = { workspace = true }
bincode = { workspace = true }
bytes = { workspace = true }
clap = { workspace = true }
futures-util = { workspace = true }
rmp-serde = { workspace = true }
serde = { workspace = true }
spider-core = { workspace = true }
spider-proto-rust = { workspace = true }
spider-task-executor = { workspace = true }
spider-tdl = { workspace = true }
spider-utils = { workspace = true }
thiserror = { workspace = true }
tokio = {
  workspace = true,
  features = [
    "io-std",
    "io-util",
    "macros",
    "process",
    "rt",
    "rt-multi-thread",
    "signal",
    "sync",
    "time"
  ]
}
tokio-util = { workspace = true, features = ["codec", "rt"] }
tonic = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
