[package]
name = "spider-storage"
version = { workspace = true }
edition = { workspace = true }
autotests = false

[lib]
name = "spider_storage"
path = "src/lib.rs"

[[bin]]
name = "spider-storage"
path = "src/bin/grpc_server.rs"

[[test]]
name = "test_spider_storage"
path = "tests/test_spider_storage.rs"

[dependencies]
async-channel = { workspace = true }
async-trait = { workspace = true }
clap = { workspace = true }
const_format = { workspace = true }
dashmap = { workspace = true }
secrecy = { workspace = true }
serde = { workspace = true }
spider-core = { workspace = true }
spider-derive = { workspace = true }
spider-proto-rust = { workspace = true }
spider-tdl = { workspace = true }
spider-utils = { workspace = true }
sqlx = { workspace = true, features = ["runtime-tokio"] }
subtle = { workspace = true }
thiserror = { workspace = true }
tokio = {
  workspace = true,
  features = ["macros", "net", "rt-multi-thread", "signal", "sync", "time"]
}
tokio-util = { workspace = true, features = ["rt"] }
tonic = { workspace = true }
tracing = { workspace = true, features = ["attributes"] }

[dev-dependencies]
anyhow = { workspace = true }
rand = { workspace = true }
serde_json = { workspace = true }
serial_test = { workspace = true }
tabled = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "sync"] }
