[package]
name = "spider-scheduler"
version = { workspace = true }
edition = { workspace = true }

[lib]
name = "spider_scheduler"
path = "src/lib.rs"

[[bin]]
name = "spider-scheduler"
path = "src/bin/grpc_server.rs"

[dependencies]
async-channel = { workspace = true }
async-trait = { workspace = true }
clap = { workspace = true }
serde = { workspace = true }
spider-core = { workspace = true }
spider-proto-rust = { workspace = true }
spider-utils = { workspace = true }
thiserror = { workspace = true }
tokio = {
  workspace = true,
  features = ["macros", "net", "rt-multi-thread", "signal", "sync", "time"]
}
tokio-util = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
dashmap = { workspace = true }
rand = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tokio-util = { workspace = true, features = ["rt"] }
