[package]
name = "em-runtime-tests"
version = { workspace = true }
edition = { workspace = true }
publish = false

[lib]
name = "em_runtime_tests"
path = "src/lib.rs"

[[test]]
name = "runtime"
path = "tests/test_runtime.rs"

[dev-dependencies]
anyhow = { workspace = true }
spider-core = { workspace = true }
spider-execution-manager = { workspace = true }
spider-tdl = { workspace = true }
test-utils = { workspace = true }
tokio = {
  workspace = true,
  features = ["macros", "rt", "rt-multi-thread", "time"]
}
