connection_pool_size: 4
host: "0.0.0.0"
port: 50052
runtime:
  advertised_endpoint:
    host: "spider-scheduler"
    port: 50052
  scheduler:
    policy: "round_robin"
    config:
      active_job_queue_capacity: 64
      cleanup_ready_task_capacity: 256
      commit_ready_task_capacity: 256
      dispatch_queue_capacity: 64
      finalizing_job_expiration_timeout_sec: 300
      ready_task_capacity: 65536
      storage_poll_timeout_ms: 10
      tick_interval_ms: 5
storage_endpoint:
  host: "spider-storage"
  port: 50051
