host: "0.0.0.0"
port: 50051
runtime:
  db_config:
    host: "spider-database"
    max_connections: 64
    name: "spider-db"
    port: 3306
  ready_queue_config:
    cleanup_capacity: 256
    commit_capacity: 256
    task_capacity: 1048576
