connection_pool_size: 4
liveness:
  scheduler_heartbeat_interval_sec: 10
  storage_heartbeat_interval_sec: 10
scheduler:
  host: "spider-scheduler"
  port: 50052
scheduler_poll_wait_ms: 1000
storage:
  host: "spider-storage"
  port: 50051
task_executor:
  bin_path: "/usr/local/bin/spider-task-executor"
  inherited_env: []
  max_log_line_bytes: 65536
  package_dir: "/opt/spider/packages"
