[project]
name = "spider-client"
version = "0.1.0"
description = "Spider client library"
requires-python = ">=3.10"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
