name: "spider-image-build"

on:
  pull_request:
    paths: &monitored_paths
      - ".cargo/**"
      - ".github/workflows/spider-image-build.yaml"
      - ".gitmodules"
      - "Cargo.lock"
      - "Cargo.toml"
      - "components/**"
      - "taskfile.yaml"
      - "taskfiles/**"
      - "tools/docker/**"
      - "tools/scripts/**"
      - "tools/yscope-dev-utils"
  push:
    branches: ["main"]
    paths: *monitored_paths
    tags: ["spider-huntsman-v*"]
  workflow_dispatch:

permissions: {}

concurrency:
  group: "${{github.workflow}}-${{github.ref}}"
  # Cancel in-progress jobs for efficiency. Exclude the `main` branch to allow uninterrupted
  # publishing of container images.
  cancel-in-progress: "${{github.ref != 'refs/heads/main'}}"

jobs:
  build-and-push:
    runs-on: "ubuntu-latest"
    permissions:
      contents: "read"
      packages: "write"
    strategy:
      matrix:
        service: ["storage", "scheduler", "worker"]
    steps:
      - uses: "actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd"  # v6.0.2
        with:
          submodules: "recursive"

      - name: "Sanitize repository name"
        id: "repo"
        run: >-
          echo "name=${GITHUB_REPOSITORY,,}" >> "$GITHUB_OUTPUT"

      - uses: "docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2"  # v3.10.0

      - uses: "docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121"  # v4.1.0
        if: "github.event_name != 'pull_request'"
        with:
          registry: "ghcr.io"
          username: "${{github.actor}}"
          password: "${{secrets.GITHUB_TOKEN}}"

      - uses: "docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804"  # v5.7.0
        id: "meta"
        with:
          images: "ghcr.io/${{steps.repo.outputs.name}}/${{matrix.service}}"
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha

      - uses: "docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4"  # v6.15.0
        with:
          context: "."
          file: "tools/docker/Dockerfile"
          target: "${{matrix.service}}"
          push: "${{github.event_name != 'pull_request'}}"
          tags: "${{steps.meta.outputs.tags}}"
          labels: "${{steps.meta.outputs.labels}}"
