name: "tdl-generated-code-checks"

on:
  pull_request:
  push:
  schedule:
    # Run daily at 00:15 UTC (the 15 is to avoid periods of high load)
    - cron: "15 0 * * *"
  workflow_dispatch:

concurrency:
  group: "${{github.workflow}}-${{github.ref}}"
  # Cancel in-progress jobs for efficiency
  cancel-in-progress: true

jobs:
  antlr-code-committed:
    name: "antlr-code-committed"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683"
        with:
          submodules: "recursive"

      - name: "Set up Java"
        uses: "actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00"
        with:
          distribution: "temurin"
          java-version: "11"

      - name: "Install task"
        shell: "bash"
        run: "npm install -g @go-task/cli@3.44.0"

      - name: "Generate parsers"
        shell: "bash"
        run: "task build:tdl-generate-parsers"

      - name: "Check if the generated parsers are the latest"
        shell: "bash"
        run:
          |
          git diff --exit-code src/spider/tdl/parser/antlr_generated
