name: "tdl-generated-code-checks"

on:
  pull_request:
  push:
  workflow_dispatch:

concurrency:
  group: "${{github.workflow}}-${{github.ref}}"
  # Cancel in-progress jobs for efficiency
  cancel-in-progress: true

jobs:
  antlr-code-committed:
    name: "antlr-code-committed"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683"
        with:
          submodules: "recursive"

      - name: "Install task"
        shell: "bash"
        run: "npm install -g @go-task/cli"

      - name: "Generate parsers"
        shell: "bash"
        run: "task build:tdl-generate-parsers"

      - name: "Check if the generated parsers are the latest"
        shell: "bash"
        run:
          |
          git status --porcelain \
            src/spider/tdl/parser/antlr_generated \
            | grep . > /dev/null \
              && exit 1 \
              || exit 0
